"""modes

Revision ID: a8ca16985e0c
Revises: 76cd36ad7dc7
Create Date: 2018-01-23 15:24:16.844450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ca16985e0c'
down_revision = '76cd36ad7dc7'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mode_name'), ['name'], unique=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('files', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('mode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_mode", 'mode', ['mode_id'], ['id'])
        batch_op.drop_column('body')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mode_id')
        batch_op.drop_column('files')
        batch_op.drop_column('comment')

    with op.batch_alter_table('mode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mode_name'))

    op.drop_table('mode')
    ### end Alembic commands ###
