"""add_File

Revision ID: c708efef60ed
Revises: d22de7f4de2d
Create Date: 2018-01-31 15:52:23.565620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c708efef60ed'
down_revision = 'd22de7f4de2d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('path', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('md5sum', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_md5sum'), ['md5sum'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_type'), ['type'], unique=False)

    op.create_table('files_in_task2',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('files')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', sa.VARCHAR(length=320), nullable=True))

    op.drop_table('files_in_task2')
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_type'))
        batch_op.drop_index(batch_op.f('ix_file_size'))
        batch_op.drop_index(batch_op.f('ix_file_path'))
        batch_op.drop_index(batch_op.f('ix_file_name'))
        batch_op.drop_index(batch_op.f('ix_file_md5sum'))

    op.drop_table('file')
    ### end Alembic commands ###
