"""add User.code

Revision ID: d22de7f4de2d
Revises: a8ca16985e0c
Create Date: 2018-01-30 09:21:16.885268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22de7f4de2d'
down_revision = 'a8ca16985e0c'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint('uq_code', ['code'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_code', type_='unique')
        batch_op.drop_column('code')

    ### end Alembic commands ###
