"""api

Revision ID: d81eff188b88
Revises: c708efef60ed
Create Date: 2018-02-26 09:22:03.652061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81eff188b88'
down_revision = 'c708efef60ed'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_name'), ['name'], unique=False)

    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('name_rus', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_name_rus'), ['name_rus'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fkey_position', 'position', ['position_id'], ['id'])
        batch_op.create_foreign_key('fkey_state', 'state', ['state_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_name_rus'))
        batch_op.drop_index(batch_op.f('ix_state_name'))

    op.drop_table('state')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_name'))

    op.drop_table('position')
    ### end Alembic commands ###
